import React, {useEffect, useRef, useState} from 'react';
import {ArrowRight, ArrowUp, List, X, CaretDown, Image as ImageIcon} from '@phosphor-icons/react';
import posts from './generated/news.json';
import {BASE, href, services, pageMeta} from './site.js';
import {About, Works, Service, News, Article, Recruit, Contact, Privacy, Complete, NewsRows} from './Pages.jsx';

export const Arrow=({size=30})=><ArrowRight size={size} weight="thin" aria-hidden="true"/>;
export function Brand(){return <span className="brand"><span className="brand-mark" style={{maskImage:`url(${href('assets/amenowa-mark.png')})`,WebkitMaskImage:`url(${href('assets/amenowa-mark.png')})`}} aria-hidden="true"/><img className="brand-word-image" src={href('assets/amenowa-wordmark.png')} alt="" width="103" height="21"/></span>;}
export function Button({to,children,secondary=false}){return <a className={`button ${secondary?'button-secondary':''}`} href={href(to)}>{children}<Arrow/></a>;}
export function Media({name='写真',className='',ratio}){return <div className={`media-placeholder ${className}`} style={ratio?{aspectRatio:ratio}:undefined} role="img" aria-label={`${name}：画像はめ込み予定`}><div className="media-label"><ImageIcon size={32} weight="thin" aria-hidden="true"/><span>画像はめ込み予定</span><small>{name}</small></div></div>;}
function Header({path}){
 const[open,setOpen]=useState(false),[worksOpen,setWorksOpen]=useState(false);const navRef=useRef(null),toggleRef=useRef(null);
 useEffect(()=>{if(!open)return;const prev=document.body.style.overflow;document.body.style.overflow='hidden';const handler=e=>{if(e.key==='Escape'){setOpen(false);toggleRef.current?.focus();}if(e.key==='Tab'){const nodes=[toggleRef.current,...navRef.current.querySelectorAll('a,button')].filter(n=>n&&n.offsetParent!==null);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){last.focus();e.preventDefault();}else if(!e.shiftKey&&document.activeElement===last){first.focus();e.preventDefault();}}};document.addEventListener('keydown',handler);return()=>{document.body.style.overflow=prev;document.removeEventListener('keydown',handler);};},[open]);
 const link=(p,label)=><a href={href(p)} aria-current={path===p?'page':undefined}>{label}</a>;
 return <header className="site-header"><a className="brand-link" href={href()} aria-label="amenowa ホーム"><Brand/></a><button ref={toggleRef} className="menu-toggle" aria-controls="main-navigation" aria-expanded={open} aria-label={open?'メニューを閉じる':'メニューを開く'} onClick={()=>setOpen(!open)}>{open?<X size={26} weight="thin"/>:<List size={28} weight="thin"/>}</button><nav id="main-navigation" ref={navRef} className={open?'navigation is-open':'navigation'} aria-label="グローバルナビゲーション">{link('','HOME')}{link('about/','ABOUT')}{link('news/','NEWS')}<div className={`nav-works ${worksOpen?'expanded':''}`} onKeyDown={e=>{if(e.key==='Escape'){setWorksOpen(false);e.currentTarget.querySelector('button')?.focus();}}}><div className="nav-works-label">{link('works/','WORKS')}<button aria-label="WORKSのページ一覧" aria-expanded={worksOpen} aria-controls="works-submenu" onClick={()=>setWorksOpen(!worksOpen)}><CaretDown size={12}/></button></div><div id="works-submenu" className="works-submenu">{services.map(s=><a key={s.slug} href={href(`works/${s.slug}/`)}>{s.name}<Arrow size={20}/></a>)}</div></div>{link('recruit/','RECRUIT')}<a className="header-contact" href={href('contact/')}>お問い合わせ<Arrow/></a></nav></header>;
}
function Footer(){return <footer className="site-footer"><div className="footer-top"><a href={href()} aria-label="amenowa ホーム"><Brand/></a><p>水の未来を、ともにつくる。</p><a className="page-top" href="#top" aria-label="ページの先頭へ"><ArrowUp size={24} weight="thin"/></a></div><div className="footer-bottom"><small>© {new Date().getFullYear()} amenowa</small><div><a href={href('privacy/')}>個人情報の取り扱い</a><a href={href('contact/')}>お問い合わせ</a></div><span className="demo-note">DESIGN PREVIEW · 画像・掲載内容は確認用です</span></div></footer>;}
export function ContactCTA(){return <section className="contact-cta"><div><span className="eyebrow">CONTACT</span><h2>水について、<br className="mobile-only"/>一緒に考えませんか。</h2><p>現場の課題から、未来の構想まで。<br/>まずは、お聞かせください。</p></div><Button to="contact/">お問い合わせ</Button></section>;}
export function WorkLinks({except}){return <div className="work-links">{services.filter(s=>s.slug!==except).map(s=><a key={s.slug} href={href(`works/${s.slug}/`)}><span>{s.name}</span><Arrow/></a>)}</div>;}
export function PageIntro({label,title,description}){return <section className="page-intro content-width"><div className="breadcrumb"><a href={href()}>HOME</a><span>/</span><span>{label}</span></div><span className="eyebrow">{label}</span><h1>{title}</h1>{description&&<p>{description}</p>}</section>;}
function Home(){return <><section className="home-hero"><div className="hero-copy"><h1><span>水を測る。水を知る。</span><span>水の未来を、ともにつくる。</span></h1><p>観測とデータから、持続可能な水利用と水の再生へ。</p><Button to="works/">事業内容を見る</Button></div><div className="hero-media"><img className="hero-photo" src={href('images/hero-river-v1.webp')} alt="緑豊かな山々の間を流れる、岩と澄んだ水の清流" width="1086" height="1448" fetchPriority="high" decoding="async"/></div></section><section className="home-concept"><div className="concept-copy"><h2>見えない水を、<br/>見える未来へ。</h2><p>降り注いだ雨は、森をうるおし、川となり、地下をめぐり、<br className="desktop-only"/>やがて海へと還っていきます。<br/>私たちは、自然のしくみに寄り添いながら、<br className="desktop-only"/>水の状態を観測し、データを読み解き、<br className="desktop-only"/>人の営みと自然の循環が調和する未来を、ともにつくります。</p></div><figure className="concept-figure"><img className="concept-art" src={href('images/water-cycle-v1.webp')} alt="雨が森や山に降り、土壌に浸透し、地下水と川を通じて海へ流れる水循環のイメージ図" width="1448" height="1086" loading="lazy" decoding="async"/><figcaption>水循環のイメージ</figcaption></figure></section><section className="home-works"><h2 className="eyebrow">WORKS</h2><div className="home-works-content"><WorkLinks/><Media name="調査・採水の現場写真"/></div></section><section className="home-news content-width"><div className="section-heading"><div><span className="eyebrow">NEWS</span><h2>お知らせ・ブログ</h2></div><a className="text-link" href={href('news/')}>すべて見る<Arrow/></a></div><NewsRows items={posts.slice(0,3)}/></section><ContactCTA/></>;}
export function App({initialPath}){const path=initialPath??decodeURIComponent(location.pathname.slice(BASE.length)).replace(/^\//,'');const s=services.find(s=>path===`works/${s.slug}/`),p=posts.find(p=>path===`news/${p.slug}/`);useEffect(()=>{document.title=p?`${p.title} | amenowa`:pageMeta(path).title;},[path,p]);let content=path===''?<Home/>:path==='about/'?<About/>:path==='works/'?<Works/>:s?<Service service={s}/>:path==='news/'?<News/>:p?<Article post={p}/>:path==='recruit/'?<Recruit/>:path==='contact/'?<Contact/>:path==='contact/complete/'?<Complete/>:path==='privacy/'?<Privacy/>:<><PageIntro label="404" title="ページが見つかりません。" description="URLをご確認いただくか、ホームからお探しください。"/><section className="content-width complete-page"><Button to="">ホームへ戻る</Button></section></>;return <><div id="top"/><a className="skip-link" href="#main">本文へスキップ</a><Header path={path}/><main id="main">{content}</main><Footer/></>;}
