import React, {useEffect, useRef, useState} from 'react';
import {ArrowRight, ArrowUp, List, X, CaretDown, Image as ImageIcon} from '@phosphor-icons/react';
import posts from './generated/news.json';
import {BASE, href, services, pageMeta} from './site.js';
import {About, Works, Service, News, Article, Recruit, Contact, Privacy, Complete, NewsRows} from './Pages.jsx';
import {Home} from './Landing.jsx';
import {Products,Product,CaseStudies,CaseStudy} from './ContentPages.jsx';
import {Services} from './Services.jsx';
import {products,supportServices} from './catalog.js';
import {ServiceDetail} from './ServiceDetail.jsx';
import cases from './generated/cases.json';
import {illustrativeMedia} from './media.js';

export const Arrow=({size=30})=><ArrowRight size={size} weight="thin" aria-hidden="true"/>;
export function Brand(){return <span className="brand"><img className="brand-mark" src={href('assets/amenowa-symbol-official.png')} alt="" width="602" height="309"/><img className="brand-word-image" src={href('assets/amenowa-wordmark-blue.png')} alt="" width="1307" height="277"/></span>;}
export function Button({to,children,secondary=false}){return <a className={`button ${secondary?'button-secondary':''}`} href={href(to)}>{children}<Arrow/></a>;}
export function Media({name='写真',className='',ratio}){
 const media=illustrativeMedia[name];
 if(media)return <div className={`media-placeholder has-image ${media.fit==='contain'?'media-illustration':''} ${className}`} style={ratio?{aspectRatio:ratio}:undefined}><img src={href(media.src)} alt={`${media.alt}（AI生成）`} width={media.width} height={media.height} loading="lazy" decoding="async" style={media.position?{objectPosition:media.position}:undefined}/></div>;
 return <div className={`media-placeholder ${className}`} style={ratio?{aspectRatio:ratio}:undefined} role="img" aria-label={`${name}：画像はめ込み予定`}><div className="media-label"><ImageIcon size={32} weight="thin" aria-hidden="true"/><span>画像はめ込み予定</span><small>{name}</small></div></div>;
}
function Header({path}){
 const[open,setOpen]=useState(false),[worksOpen,setWorksOpen]=useState(false);const navRef=useRef(null),toggleRef=useRef(null);
 useEffect(()=>{if(!open)return;const prev=document.body.style.overflow;document.body.style.overflow='hidden';const handler=e=>{if(e.key==='Escape'){setOpen(false);toggleRef.current?.focus();}if(e.key==='Tab'){const nodes=[toggleRef.current,...navRef.current.querySelectorAll('a,button')].filter(n=>n&&n.offsetParent!==null);const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){last.focus();e.preventDefault();}else if(!e.shiftKey&&document.activeElement===last){first.focus();e.preventDefault();}}};document.addEventListener('keydown',handler);return()=>{document.body.style.overflow=prev;document.removeEventListener('keydown',handler);};},[open]);
 const link=(p,label)=><a href={href(p)} aria-current={path===p?'page':undefined}>{label}</a>;
 return <header className="site-header"><a className="brand-link" href={href()} aria-label="amenowa ホーム"><Brand/></a><button ref={toggleRef} className="menu-toggle" aria-controls="main-navigation" aria-expanded={open} aria-label={open?'メニューを閉じる':'メニューを開く'} onClick={()=>setOpen(!open)}>{open?<X size={26} weight="thin"/>:<List size={28} weight="thin"/>}</button><nav id="main-navigation" ref={navRef} className={open?'navigation is-open':'navigation'} aria-label="グローバルナビゲーション">{link('','HOME')}<div className={`nav-works ${worksOpen?'expanded':''}`} onKeyDown={e=>{if(e.key==='Escape'){setWorksOpen(false);e.currentTarget.querySelector('button')?.focus();}}}><div className="nav-works-label">{link('products/','PRODUCTS')}<button aria-label="PRODUCTSのページ一覧" aria-expanded={worksOpen} aria-controls="works-submenu" onClick={()=>setWorksOpen(!worksOpen)}><CaretDown size={12}/></button></div><div id="works-submenu" className="works-submenu">{products.map(s=><a key={s.slug} href={href(`products/${s.slug}/`)}>{s.name}<Arrow size={20}/></a>)}</div></div>{link('services/','SERVICES')}{link('case-study/','CASE STUDY')}{link('insights/','INSIGHTS')}{link('about/','ABOUT')}<a className="header-contact" href={href('contact/')}>お問い合わせ<Arrow/></a></nav></header>;
}
function Footer(){return <footer className="site-footer"><div className="footer-top"><a href={href()} aria-label="amenowa ホーム"><Brand/></a><p>水と自然を、未来につなぐ。</p><a className="page-top" href="#top" aria-label="ページの先頭へ"><ArrowUp size={24} weight="thin"/></a></div><div className="footer-bottom"><small>© {new Date().getFullYear()} amenowa</small><div><a href={href('recruit/')}>採用情報</a><a href={href('privacy/')}>個人情報の取り扱い</a><a href={href('contact/')}>お問い合わせ</a></div></div></footer>;}
export function ContactCTA(){return <section className="contact-cta"><div><span className="eyebrow">CONTACT</span><h2>水と自然について、<br className="mobile-only"/>一緒に考えませんか。</h2><p>現場の課題から、未来の構想まで。<br/>まずは、お聞かせください。</p></div><Button to="contact/">お問い合わせ</Button></section>;}
export function WorkLinks({except}){return <div className="work-links">{services.filter(s=>s.slug!==except).map(s=><a key={s.slug} href={href(`works/${s.slug}/`)}><span>{s.name}</span><Arrow/></a>)}</div>;}
export function PageIntro({label,title,description}){return <section className="page-intro content-width"><div className="breadcrumb"><a href={href()}>HOME</a><span>/</span><span>{label}</span></div><span className="eyebrow">{label}</span><h1>{title}</h1>{description&&<p>{description}</p>}</section>;}
export function App({initialPath}){const path=initialPath??decodeURIComponent(location.pathname.slice(BASE.length)).replace(/^\//,'');const support=supportServices.find(s=>path===`services/${s.slug}/`),product=products.find(s=>path===`products/${s.slug}/`),study=cases.find(s=>path===`case-study/${s.slug}/`),s=services.find(s=>path===`works/${s.slug}/`),p=posts.filter(p=>!p.externalUrl).find(p=>path===`news/${p.slug}/`);useEffect(()=>{document.title=p?`${p.title} | amenowa`:pageMeta(path).title;},[path,p]);let content=path===''?<Home/>:path==='products/'?<Products/>:product?<Product product={product}/>:path==='services/'?<Services/>:support?<ServiceDetail service={support}/>:path==='case-study/'?<CaseStudies/>:study?<CaseStudy item={study}/>:path==='about/'?<About/>:path==='works/'?<Works/>:s?<Service service={s}/>:(path==='news/'||path==='insights/')?<News/>:p?<Article post={p}/>:path==='recruit/'?<Recruit/>:path==='contact/'?<Contact/>:path==='contact/complete/'?<Complete/>:path==='privacy/'?<Privacy/>:<><PageIntro label="404" title="ページが見つかりません。" description="URLをご確認いただくか、ホームからお探しください。"/><section className="content-width complete-page"><Button to="">ホームへ戻る</Button></section></>;return <><div id="top"/><a className="skip-link" href="#main">本文へスキップ</a><Header path={path}/><main id="main">{content}</main><Footer/></>;}
