import {ArrowUpRight} from '@phosphor-icons/react';
import {Arrow,Button,Media,PageIntro,ContactCTA} from './App.jsx';
import {href} from './site.js';
import {products,supportServices} from './catalog.js';
import cases from './generated/cases.json';

export function ProductVisual({product,className=''}) {
  return product.imageSrc
    ? <figure className={`product-visual ${className}`}><div className={`product-visual-stage ${product.slug==='meguru'?'product-visual-phones':''}`}>{product.slug==='meguru'?product.screens.slice(0,3).map(screen=><img key={screen.name} src={href(screen.src)} alt={`${product.name} ${screen.name}のサンプル画面`} width={screen.width} height={screen.height} loading="lazy" decoding="async"/>):<img src={href(product.imageSrc)} alt={product.imageAlt} width={product.imageWidth} height={product.imageHeight} loading="lazy" decoding="async"/>}</div><figcaption>{product.screenNote||'画面は提供資料に基づくサンプルです。'}</figcaption></figure>
    : <Media className={`product-visual ${className}`} name={product.image}/>;
}

export function ProductOverview(){return <figure className="product-overview"><div className="product-overview-stage">{products.map(product=><div key={product.slug}>{product.imageSrc?<img src={href(product.imageSrc)} alt={`${product.name}のサンプル画面`} width={product.imageWidth} height={product.imageHeight} loading="lazy" decoding="async"/>:<Media name={product.image}/>}</div>)}</div><figcaption>AquaInsights / MEGURU</figcaption></figure>;}

function ProductScreen({product,screen}){return <figure>{screen.src?<a className="product-screen-link" href={href(screen.src)} target="_blank" rel="noopener" aria-label={`${product.name} ${screen.name}の画面を拡大（新しいタブ）`}><img src={href(screen.src)} alt={screen.alt} width={screen.width} height={screen.height} loading="lazy" decoding="async"/></a>:<Media name={`${product.name} / ${screen.name}`} ratio={product.slug==='meguru'?'0.56':'1.6'}/>}<figcaption><span>{screen.name}</span>{screen.src&&<a className="screen-enlarge" href={href(screen.src)} target="_blank" rel="noopener" aria-label={`${screen.name}の画面を拡大（新しいタブ）`}>拡大する<ArrowUpRight size={13} aria-hidden="true"/></a>}</figcaption></figure>;}

export function ProductLinks(){return <div className="work-links product-links">{products.map(product=><a key={product.slug} href={href(`products/${product.slug}/`)}><span><strong>{product.name}</strong><small>{product.slug==='aquainsights'?'水と自然を知る':'行動につなげる'}</small></span><Arrow/></a>)}</div>;}

export function Products(){return <><PageIntro label="PRODUCTS" title="知ることから、行動へ。" description="水と自然を理解し、地域の行動につなげる。2つのプラットフォームをご紹介します。"/><section className="services-index content-width">{products.map((p,i)=><article className="service-index" key={p.slug}><a className="service-index-image" href={href(`products/${p.slug}/`)} aria-label={`${p.name}を見る`}><ProductVisual product={p}/></a><div><span className="eyebrow">0{i+1} / {p.english}</span><h2><a href={href(`products/${p.slug}/`)}>{p.name}</a></h2><p>{p.intro}</p><a className="text-link" href={href(`products/${p.slug}/`)}>詳しく見る<Arrow/></a></div></article>)}</section><ContactCTA/></>;}

export function Product({product:p}){return <><div className="breadcrumb content-width"><a href={href()}>HOME</a><span>/</span><a href={href('products/')}>PRODUCTS</a><span>/</span><span>{p.name}</span></div><section className="service-hero"><div><span className="eyebrow">{p.english}</span><p className="service-name">{p.name}</p><h1>{p.headline.map(line=><span key={line}>{line}</span>)}</h1><p>{p.intro}</p><a className="text-link" href="#support">できることを見る<Arrow/></a></div><ProductVisual product={p}/></section><section className="service-lead content-width"><span className="eyebrow">OUR APPROACH</span><h2>{p.lead}</h2><p>{p.body}</p></section><section id="support" className="support-section content-width"><div className="section-heading"><div><span className="eyebrow">WHAT WE DO</span><h2>できること</h2></div></div><div className="support-grid">{p.items.map(([title,description],i)=><article key={title}><span className="support-number">0{i+1}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section><section className="product-screens content-width"><span className="eyebrow">PRODUCT VIEW</span><h2>{p.slug==='aquainsights'?'自然を理解するための情報。':'参加から、次の行動まで。'}</h2>{p.screenNote&&<p className="product-screen-note">{p.screenNote}</p>}<div className={p.slug==='meguru'?'screen-placeholders screen-placeholders-mobile':'screen-placeholders'}>{p.screens.map(screen=><ProductScreen key={screen.name} product={p} screen={screen}/>)}</div></section><section className="related-works content-width"><span className="eyebrow">PRODUCTS</span><h2>プロダクトについて</h2><ProductLinks/></section><ContactCTA/></>;}

export function Services(){return <><PageIntro label="SERVICES" title="ともに考え、現場で動かす。" description="プロダクトに加えて、戦略づくりから現場の実装、社会への発信まで伴走します。"/><section className="services-index content-width">{supportServices.map((s,i)=><article id={s.slug} className="service-index" key={s.slug}><Media className="service-index-image" name={s.image}/><div><span className="eyebrow">0{i+1} / {s.english}</span><h2>{s.name}</h2><p>{s.description}</p><a className="text-link" href={href('contact/')}>相談する<Arrow/></a></div></article>)}</section><ContactCTA/></>;}

export function CaseVisual({item,className=''}){return item.image?<img className={`case-photo ${className}`} src={item.image.startsWith('/uploads/')?href(item.image):item.image} alt={item.imageAlt} loading="lazy"/>:<Media className={className} name={`${item.title}の活動写真`}/>;}

export function CaseStudies(){return <><PageIntro label="CASE STUDY" title="構想から、地域の実装へ。" description="企業や地域とともに、水と自然の課題に向き合う取り組み。"/><section className="services-index content-width">{cases.length?cases.map(item=><article className="service-index" key={item.slug}><a className="service-index-image" href={href(`case-study/${item.slug}/`)} aria-label={`${item.title}の取り組みを見る`}><CaseVisual item={item}/></a><div><span className="eyebrow">{item.client}</span><h2>{item.title}</h2><p>{item.excerpt}</p><a className="text-link" href={href(`case-study/${item.slug}/`)}>取り組みを見る<Arrow/></a></div></article>):<p>事例の掲載準備中です。</p>}</section><ContactCTA/></>;}

export function CaseStudy({item}){return <><div className="breadcrumb content-width"><a href={href()}>HOME</a><span>/</span><a href={href('case-study/')}>CASE STUDY</a><span>/</span><span>{item.title}</span></div><section className="service-hero"><div><span className="eyebrow">CASE STUDY / {item.client}</span><p className="service-name">{item.title}</p><h1>{item.headline}</h1><p>{item.excerpt}</p><a className="text-link" href="#journey">取り組みの流れを見る<Arrow/></a></div><CaseVisual item={item}/></section><section id="journey" className="case-journey content-width"><span className="eyebrow">OUR JOURNEY</span><h2>取り組みの流れ</h2><ol className="case-timeline">{item.timeline.map((step,i)=><li key={i}><span className="timeline-number">{String(i+1).padStart(2,'0')}</span><div><h3>{step.title}</h3><p>{step.description}</p><p className="timeline-detail">{step.detail==='未定'?'詳細・実施時期：未定':step.detail}</p></div></li>)}</ol></section>{item.html&&<section className="article-content prose" dangerouslySetInnerHTML={{__html:item.html}}/>}<section className="related-works content-width"><span className="eyebrow">PRODUCTS</span><h2>知ることを、行動へ。</h2><ProductLinks/></section><ContactCTA/></>;}

export function ArticleSource({url}){return url?<p className="article-source"><a href={url}>元の記事を読む<ArrowUpRight size={18}/></a></p>:null;}
