import React,{useState} from 'react';
import {CaretDown, Check, MagnifyingGlass} from '@phosphor-icons/react';
import {services,href,formatDate} from './site.js';
import posts from './generated/news.json';
import {Media,Arrow,Button,PageIntro,WorkLinks,ContactCTA} from './App.jsx';
import {TeamSection} from './Team.jsx';
import {ArticleSource} from './ContentPages.jsx';
import {ArrowUpRight} from '@phosphor-icons/react';
export {Contact} from './Contact.jsx';
const companyBusinessActivities = [
  'AquaInsights（水と自然を知るためのプラットフォーム）',
  'MEGURU（環境活動を実行につなげるプラットフォーム）',
  '水・自然資本に関するコンサルティング',
  '現場実装・環境教育',
  '情報開示・ブランディング'
];
export function Works(){return <><PageIntro label="WORKS" title="水の課題に、向き合う。" description="水を知り、使い方を考え、循環を育てる。課題に応じた支援をご提案します。"/><section className="services-index content-width">{services.map((s,i)=><article className="service-index" key={s.slug}><a href={href(`works/${s.slug}/`)} className="service-index-image" aria-label={`${s.name}を見る`}><Media name={s.image}/></a><div><span className="eyebrow">0{i+1} / {s.english}</span><h2><a href={href(`works/${s.slug}/`)}>{s.name}</a></h2><p>{s.intro}</p><a className="text-link" href={href(`works/${s.slug}/`)}>詳しく見る<Arrow/></a></div></article>)}</section><ContactCTA/></>;}
export function Service({service:s}){return <><div className="breadcrumb content-width"><a href={href()}>HOME</a><span>/</span><a href={href('works/')}>WORKS</a><span>/</span><span>{s.name}</span></div><section className="service-hero"><div><span className="eyebrow">{s.english}</span><p className="service-name">{s.name}</p><h1>{s.headline.map(l=><span key={l}>{l}</span>)}</h1><p>{s.intro}</p><a className="text-link" href="#support">支援内容を見る<CaretDown size={20} weight="thin"/></a></div><Media name={s.image}/></section><section className="service-lead content-width"><span className="eyebrow">OUR APPROACH</span><h2>{s.lead}</h2><p>{s.body}</p></section><section id="support" className="support-section content-width"><div className="section-heading"><div><span className="eyebrow">WHAT WE DO</span><h2>支援内容</h2></div></div><div className="support-grid">{s.items.map(([t,b],i)=><article key={t}><span className="support-number">0{i+1}</span><h3>{t}</h3><p>{b}</p></article>)}</div><Media className="service-diagram" name={`${s.name}の説明図`} ratio="2.5"/></section><section className="deliverables content-width"><h2>ご相談いただけること</h2><ul>{s.deliverables.map(t=><li key={t}><Check weight="light" aria-hidden="true"/>{t}</li>)}</ul></section><section className="related-works content-width"><span className="eyebrow">RELATED WORKS</span><h2>その他の事業</h2><WorkLinks except={s.slug}/></section><ContactCTA/></>;}
export function About(){return <><PageIntro label="ABOUT" title="amenowa ― 天の環" description="自然と人、科学と事業、企業と地域をつなぐ。"/><section className="about-mission content-width"><Media name="水・森林・地域の風景"/><div><span className="eyebrow">OUR MISSION</span><h2>水と自然を知る。<br/>守り、育てる。<br/>未来につなぐ。</h2><p>amenowaは「天の環」。「天」は水、「環」は循環。水と自然、人の営みのつながりを見つめています。</p><p>企業や自治体とともに、水や自然の状態を理解し、地域の行動につなげ、その成果を社会へ伝える会社です。</p></div></section><section className="about-message content-width"><div><span className="eyebrow">MESSAGE</span><h2>まず、知ることから。<br/>ともに、未来へ。</h2><p>代表メッセージ：未定</p><p className="signature">株式会社amenowa<br/>代表取締役 <span>岩永 朝陽</span></p></div><img className="representative-photo" src={href('images/representative-asahi.jpg')} alt="株式会社amenowa 代表取締役 岩永 朝陽" width="800" height="800" loading="lazy" decoding="async"/></section><TeamSection/><section className="company-section content-width"><span className="eyebrow">COMPANY</span><h2>会社概要</h2><dl className="information-list"><div><dt>会社名</dt><dd>株式会社amenowa</dd></div><div><dt>代表者</dt><dd>代表取締役 岩永 朝陽</dd></div><div><dt>事業内容</dt><dd><ul className="company-business-list">{companyBusinessActivities.map(activity=><li key={activity}>{activity}</li>)}</ul></dd></div><div><dt>所在地</dt><dd>山梨県北杜市大泉町西井出8240</dd></div><div><dt>設立日</dt><dd><time dateTime="2023-11-23">2023年11月23日</time></dd></div></dl></section><ContactCTA/></>;}
export function NewsRows({items}){return <div className="news-rows">{items.map(p=><a className="news-row" href={p.externalUrl||href(`news/${p.slug}/`)} aria-label={p.externalUrl?`${p.title}（外部記事）`:undefined} key={p.slug}><time dateTime={p.date}>{formatDate(p.date)}</time><span className="category-label">{p.category}</span><h3>{p.title}</h3>{p.externalUrl?<ArrowUpRight size={26} weight="thin" aria-hidden="true"/>:<Arrow size={26}/>}</a>)}</div>;}
export function News(){const[category,setCategory]=useState('すべて'),[query,setQuery]=useState(''),[page,setPage]=useState(1);const cats=['すべて','お知らせ','ブログ','プレスリリース','note'];const filtered=posts.filter(p=>(category==='すべて'||p.category===category)&&`${p.title} ${p.excerpt}`.includes(query.trim()));const pages=Math.ceil(filtered.length/6);return <><PageIntro label="INSIGHTS" title="お知らせ・ブログ" description="水と自然を知り、行動につなげる。amenowaからの情報と読みもの。"/><section className="news-section content-width"><div className="news-controls"><div className="category-filters" aria-label="記事カテゴリー">{cats.map(c=><button key={c} aria-pressed={category===c} onClick={()=>{setCategory(c);setPage(1);}}>{c}</button>)}</div><label className="news-search"><MagnifyingGlass size={19}/><input type="search" placeholder="記事を検索" aria-label="記事を検索" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/></label></div><p className="result-count" aria-live="polite">{filtered.length}件の記事</p>{filtered.length?<NewsRows items={filtered.slice((page-1)*6,page*6)}/>:<div className="empty-state"><h2>該当する記事がありません。</h2><p>キーワードやカテゴリーを変えてお試しください。</p><button className="text-link" onClick={()=>{setQuery('');setCategory('すべて');}}>条件をリセット<Arrow/></button></div>}{pages>1&&<nav className="pagination" aria-label="記事のページ">{Array.from({length:pages},(_,i)=><button key={i} aria-current={page===i+1?'page':undefined} onClick={()=>setPage(i+1)}>{i+1}</button>)}</nav>}</section><ContactCTA/></>;}
export function Article({post:p}){const img=p.image?.startsWith('/uploads/')?href(p.image):p.image;return <><div className="breadcrumb content-width"><a href={href()}>HOME</a><span>/</span><a href={href('insights/')}>INSIGHTS</a></div><article className="article-content"><header><div className="article-meta"><time dateTime={p.date}>{formatDate(p.date)}</time><span className="category-label">{p.category}</span></div><h1>{p.title}</h1></header>{img?<img className="article-image" src={img} alt={p.imageAlt} width="960" height="540"/>:null}<div className="prose" dangerouslySetInnerHTML={{__html:p.html}}/><ArticleSource url={p.sourceUrl}/><a href={href('insights/')} className="text-link back-link">お知らせ・ブログ一覧へ<Arrow/></a></article><ContactCTA/></>;}
export function Recruit(){return <><PageIntro label="RECRUIT" title={<>水の未来を、<br/>ともにつくる仲間へ。</>} description="異なる専門性が出会い、地域の水に向き合う。"/><section className="recruit-visual content-width"><Media name="調査・フィールドワーク・チームの写真" ratio="2.2"/></section><section className="recruit-copy content-width"><span className="eyebrow">WORK WITH US</span><h2>現場から考える。<br/>分野を越えて、つながる。</h2><p>水、森林、地質、IoT、データ、地域との対話。自然と社会の両方に向き合う仕事には、多様な視点が必要です。</p><p>経験や専門性を活かし、次世代に水のある風景を残していく。amenowaの取り組みに関心をお持ちの方は、お問い合わせください。</p></section><section className="recruit-info content-width"><h2>採用に関するご相談</h2><p>募集職種・条件は確認のうえ掲載予定です。現在の募集状況については、お問い合わせください。</p><Button to="contact/?subject=recruit">採用について問い合わせる</Button></section><ContactCTA/></>;}
export function Privacy(){return <><PageIntro label="PRIVACY" title="個人情報の取り扱い"/><section className="article-content prose"><p className="form-demo-note">デザイン確認用の掲載案です。正式な方針は本番公開前に確認・確定します。デモのフォームでは入力内容を送信・保存しません。</p><h2>お問い合わせでお預かりする情報</h2><p>お名前、メールアドレス、会社名・団体名、お問い合わせ内容を、ご相談への回答と必要なご連絡に使用する方針です。</p><h2>情報の管理</h2><p>本番公開前に、情報を取り扱う担当者、保存期間、外部フォームサービスの利用条件と委託関係を確認し、正式な内容を掲載します。</p><h2>ご相談窓口</h2><p>個人情報の取り扱いに関する窓口は、本番公開時にご案内します。</p><Button to="contact/">お問い合わせへ</Button></section></>;}
export function Complete(){const live=import.meta.env.VITE_CONTACT_MODE==='live';return <><PageIntro label="CONTACT" title={live?'お問い合わせの送信手続きが完了しました。':'お問い合わせ完了画面（デモ）'}/><section className="complete-page content-width"><p>{live?'内容を確認のうえ、担当者よりご連絡いたします。':'このデモではメールの送信・入力内容の保存は行っていません。'}</p><p className="sample-note">このページの表示だけではメールの到達を確認できません。</p><Button to="">ホームへ戻る</Button></section></>;}
